// Public-reference knowledge, not training examples or calibrated rejection thresholds.
// Short, independently written inspection prompts; linked source assets are not copied.
export const REFERENCE_VERSION='fresh-reference-2026-09-22-v1';
export const REFERENCE_DATE='2026-09-22';
export const CATEGORIES=[{id:'meat',name:'축산'},{id:'vegetable',name:'채소'},{id:'fruit',name:'과일'},{id:'seafood',name:'수산'}];
export const SOURCES={
  gs:{title:'GS리테일 · 선도 지킴이·안전 위생관리',url:'https://hpimg.gsretail.com/gsretail/ko/esg/customer-satisfaction',scope:'공개 운영 원칙. SKU별 검수·반품 허용치가 아님.'},
  lotte:{title:'롯데마트 · 품질보증제',url:'https://company.lottemart.com/service/quality.asp',scope:'고객 품질보증 사례. GS 입고 검수나 해피콜 규정이 아님.'},
  meat:{title:'USDA FSIS · 육류의 색 변화와 변질',url:'https://ask.fsis.usda.gov/article/Does-a-change-in-color-indicate-spoilage',scope:'색만으로 변질을 확정할 수 없다는 관찰 원칙.'},
  chicken:{title:'USDA FSIS · 닭고기 품질과 색',url:'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/poultry/chicken-farm-table',scope:'생닭 피부색 차이 참고. 미국 등급·법규를 국내 기준으로 적용하지 않음.'},
  produce:{title:'FDA · 과채류 구매·취급',url:'https://www.fda.gov/consumers/consumer-updates/7-tips-cleaning-fruits-vegetables',scope:'상처 확인과 절단 과채류의 냉장 취급 참고.'},
  lettuce:{title:'UC Davis · 결구상추(양상추)',url:'https://postharvest.ucdavis.edu/produce-facts-sheets/lettuce-crisphead',scope:'결구상추의 외관 품질. 모든 엽채류에 같은 허용치를 적용하지 않음.'},
  broccoli:{title:'UC Davis · 브로콜리',url:'https://postharvest.ucdavis.edu/produce-facts-sheets/broccoli',scope:'꽃봉오리·황화 등 수확 후 품질 참고.'},
  cucumber:{title:'UC Davis · 오이',url:'https://postharvest.ucdavis.edu/produce-facts-sheets/cucumber',scope:'표면 손상·황화·수분 손실 참고.'},
  banana:{title:'UC Davis · 바나나',url:'https://postharvest.ucdavis.edu/produce-facts-sheets/banana',scope:'숙도와 손상·부패 구분 참고.'},
  bananaRetail:{title:'Chiquita · 매장 바나나 품질관리',url:'https://chiquitabrands.com/wp-content/uploads/2020/09/Chiquita-Whitepaper-Quality-on-Shelf.pdf',scope:'공급사의 매장 취급 참고. GS 공식 허용치가 아님.'},
  peach:{title:'UC Davis · 복숭아·천도복숭아',url:'https://postharvest.ucdavis.edu/produce-facts-sheets/peach',scope:'품종별 숙도·상처·내부 장해 참고.'},
  watermelon:{title:'UC Davis · 수박',url:'https://postharvest.ucdavis.edu/produce-facts-sheets/watermelon',scope:'통수박 외관과 숙도 참고. 사진으로 당도를 측정하지 않음.'},
  strawberry:{title:'UC Davis · 딸기',url:'https://postharvest.ucdavis.edu/produce-facts-sheets/strawberry',scope:'외관 손상·곰팡이 참고.'},
  seafood:{title:'FDA · 신선·냉동 수산물 구매와 취급',url:'https://www.fda.gov/food/buy-store-serve-safe-food/selecting-and-serving-fresh-and-frozen-seafood-safely',scope:'제품 형태별 관찰 참고. 국내 납품 온도·검사 규격을 대신하지 않음.'}
};
export const COMMON={
  status:'public-reference-not-gs-approved',
  photoChecks:['상품 전체와 이상 부위를 각각 기록하고 바코드·라벨을 실물과 대조','포장 찢김·밀봉 손상·외부 누액·이물 의심 흔적 확인','반사·흐림·가림이 있으면 없는 결함으로 처리하지 않고 재촬영'],
  fieldChecks:['입고일·상품명·판매단위·제조/포장 정보·표시기한 확인','제품 표시와 승인된 납품 규격에 따라 실제 온도·배송 기록 확인','수량 부족과 선도 불량 수량을 별도로 확인'],
  decisionPolicy:{
    pass:'사진에서 관찰 가능한 범위의 외관 적합만 뜻합니다. 식품 안전·판매 승인을 보증하지 않습니다.',
    fail:'명확한 외관 손상은 실물을 확인하고 승인된 상품 규격과 대조해 부적합 근거로 기록합니다.',
    review:'사진이 불명확하거나 냄새·온도·내부 상태가 필요한 경우 추가 확인으로 남깁니다.',
    noPhotoSafetyCertification:true,noInventedTemperatureLimits:true,unknownIsNotNormal:true
  },
  limitations:['공개 자료를 토대로 작성한 참고 기준이며 GS 내부 검수·반품 기준이 아닙니다.','품종·계절·가공 상태·포장 방식에 따라 적용 항목이 달라집니다.','사진으로 병원체·잔류농약·중금속·히스타민·소비기한을 추정하지 않습니다.','밀봉 상품을 냄새 확인만을 위해 개봉하지 않습니다. 확인 불가 항목은 담당자에게 연결합니다.'],
  sources:['gs','lotte','produce','meat','seafood']
};
const profile=(id,category,name,scope,visible,field,exceptions,photo,sources,productType=null)=>({id,category,name,scope,visible,field,exceptions,photo,sources,productType,
  aiStatus:productType?'existing-appearance-model':'reference-only',thresholdStatus:'requires-approved-sku-spec',trainingStatus:'not-fine-tuned'});
export const PROFILES=[
  profile('beef','meat','소고기','양념하지 않은 생육·포장육',
    ['표면의 이물·비정상 부착물·포장 손상 확인','변색 위치를 기록하되 색 하나로 부패를 확정하지 않기'],
    ['이취·끈적임·점액은 승인된 현장 절차로 확인','부위·포장 방식·냉장/냉동 표시와 온도 기록 대조'],
    ['밝은 빨강·어두운 색·갈색 변화만으로 정상 또는 부패를 확정하지 않습니다.'],
    '포장 전체와 변색 부위를 같은 조명에서 촬영합니다.',['meat']),
  profile('pork','meat','돼지고기','양념하지 않은 생육·포장육',
    ['표면 상태와 누액이 포장 안인지 밖인지 구분','변색과 포장 밀봉 이상을 따로 기록'],
    ['이취·점착성 등은 현장 확인','상품 표시와 보관·운송 온도 기록 대조'],
    ['육색 하나와 포장 안의 액체만으로 부패를 단정하지 않습니다.'],
    '전체 포장·밀봉부·의심 부위를 촬영합니다.',['meat']),
  profile('chicken','meat','닭고기','가열·양념하지 않은 생닭',
    ['피부 찢김·노출 부위·포장 밖 누액 확인','비정상 부착물과 색 변화를 함께 기록'],
    ['냉장/냉동 구분·온도 기록 확인','이취·점액 의심 시 담당자 실물 확인'],
    ['크림색부터 노란색까지의 피부색 차이는 그 자체로 선도 불량을 뜻하지 않습니다.'],
    '트레이 전체와 포장 가장자리를 촬영합니다.',['meat','chicken']),
  profile('lettuce','vegetable','양상추','결구상추; 다른 엽채류는 별도 규격 확인',
    ['시듦·수축·잎 파손 확인','젖어 무너진 조직과 곰팡이 의심 부위 확인'],
    ['겹친 안쪽 잎과 실물의 탄력 확인','냉장 표시·온도 기록·이취 여부 확인'],
    ['밑동 절단면의 갈변만으로 전체 품질 저하를 단정하지 않습니다.'],
    '겉잎·밑동·의심 부위를 각각 기록합니다.',['lettuce','produce']),
  profile('broccoli','vegetable','브로콜리','생 브로콜리',
    ['꽃봉오리의 벌어짐과 황화 확인','꽃송이의 무너짐·곰팡이 의심 부위 확인'],
    ['줄기·꽃송이 탄력과 보관 이력 확인'],
    ['황화는 상품성 저하 단서이며 식품 안전성 판정과는 구분합니다. 품종의 정상 색을 확인합니다.'],
    '꽃봉오리가 보이는 윗면과 줄기를 촬영합니다.',['broccoli','produce']),
  profile('cucumber','vegetable','오이','생 오이',
    ['심한 주름·황화·깊은 상처 확인','표면의 움푹 팬 부분·물러 무너진 부분 확인'],
    ['품종·숙도·실제 경도·저온 노출 이력 확인'],
    ['색과 모양은 품종 차이가 큽니다. 표면 함몰만으로 원인을 특정하지 않습니다.'],
    '오이 전체와 반대쪽 면도 확인합니다.',['cucumber','produce']),
  profile('banana','fruit','바나나','통바나나·봉지 포장; 기존 2개 SKU 연결',
    ['껍질 균열·과육 노출·누액 확인','꼭지 곰팡이 의심·심한 함몰과 붕괴 확인'],
    ['포장에 가려진 면·실제 경도·냄새 확인','묶음/봉 단위의 불량 수량 확인'],
    ['초록색이나 작은 갈색 반점만으로 부적합 처리하지 않습니다.','넓은 검변은 후숙·저온 장해·손상 가능성을 구분해 확인합니다.'],
    '포장 반사를 줄이고 껍질·꼭지가 모두 보이게 촬영합니다.',['banana','bananaRetail'],'banana'),
  profile('peach','fruit','복숭아','통복숭아; 연한 품종 포함',
    ['곰팡이 의심 군집·찌그러짐·갈라짐·과즙 누출 확인'],
    ['품종별 정상 경도와 눌림 여부 확인','가려진 밑면과 내부 장해는 별도 확인'],
    ['자연 솜털·정상 착색을 곰팡이로 단정하지 않습니다.','말랑한 품종의 정상 숙도와 부패를 사진만으로 구분하기 어려울 수 있습니다.'],
    '솜털과 의심 반점이 구별될 정도로 가까이 촬영합니다.',['peach','produce'],'peach'),
  profile('watermelon','fruit','수박','자르지 않은 통수박',
    ['깊은 균열·압궤·함몰·누액 확인','부패 의심 병반과 표면 파손 확인'],
    ['무게는 저울, 당도는 승인된 측정 절차로 확인','내부 상태는 외관과 별도 확인'],
    ['바닥의 노란 착색은 정상적인 숙도 단서일 수 있습니다.','통수박 사진으로 속의 상태·고당도·6kg 충족을 확정하지 않습니다.'],
    '전체 형태·바닥·손상 부위를 촬영합니다.',['watermelon'],'watermelon'),
  profile('strawberry','fruit','딸기','생딸기·투명팩',
    ['곰팡이 의심 부위·짓무름·눌린 과실 확인','팩 바닥의 으깨진 과실과 누액 확인'],
    ['아래층 과실·실제 탄력·냉장 이력 확인'],
    ['색만으로 맛·당도·안전성을 추정하지 않습니다.'],
    '팩 윗면과 보이는 바닥면을 촬영합니다.',['strawberry','produce']),
  profile('whole-fish','seafood','생선 · 원물','냉장 생선; 해동 제품은 별도 확인',
    ['눈의 투명도·광택과 보이는 아가미 상태를 함께 확인'],
    ['냄새·탄력·냉장/해동 표시·온도 기록 확인'],
    ['해동 생선에 생물의 눈·아가미 기준을 그대로 적용하지 않습니다.'],
    '포장을 해치지 않는 범위에서 전체와 머리를 기록합니다.',['seafood']),
  profile('fish-fillet','seafood','생선 · 절단육','비가열 필렛·토막 생선',
    ['절단면 가장자리의 건조·변색·파손 확인'],
    ['냄새·탄력·해동 표시·온도 기록 확인'],
    ['어종·처리·포장에 따라 색이 달라 색만으로 선도를 확정하지 않습니다.'],
    '단면·가장자리·포장 라벨을 기록합니다.',['seafood']),
  profile('shrimp','seafood','새우 등 갑각류 살','비가열 살; 조리 제품에는 적용하지 않음',
    ['살의 투명감·색 변화·포장 손상 확인'],
    ['제품 종류·냄새·보관 이력 확인'],
    ['조리·냉동 상태와 품종에 맞는 상품 규격을 먼저 확인합니다.'],
    '살과 포장을 같이 기록합니다.',['seafood']),
  profile('live-shellfish','seafood','살아 있는 이매패류','조개·굴·홍합 원물; 탈각·냉동품 제외',
    ['깨진 껍데기 확인'],
    ['생존 반응과 생산·유통 표시를 현장 확인'],
    ['열린 껍데기 한 장면만으로 생사를 단정하지 않습니다.'],
    '전체·깨진 부분·라벨을 기록합니다.',['seafood']),
  profile('frozen-seafood','seafood','냉동 수산물','냉동 표시 제품',
    ['찢어진 포장·심한 성에·얼음 결정 확인'],
    ['단단한 냉동 상태·온도·배송 이력 확인'],
    ['성에만으로 재냉동을 확정하지 않습니다.'],
    '포장·얼음 흔적·라벨을 기록합니다.',['seafood'])
];
export function getFreshnessProfile(productType){return PROFILES.find(p=>p.productType===productType)||null;}
export function referenceDataset(){return {version:REFERENCE_VERSION,reviewedAt:REFERENCE_DATE,modelWeightsUpdated:false,gsInternalSpecificationVerified:false,categories:CATEGORIES,common:COMMON,profiles:PROFILES,sources:SOURCES};}
